# Changes here will be overwritten by Copier
_commit: 0.9.10
_src_path: https://github.com/pawamoy/copier-pdm.git
author_email: erwan.schild@e-i.com
author_fullname: Erwan Schild
author_username: erwanschild
copyright_date: '2022'
copyright_holder: Erwan Schild
copyright_holder_email: erwan.schild@e-i.com
copyright_license: CeCILL-C License v1.0
project_description: An annotation tool for NLP data based on Interactive Clustering methodology.
project_name: Interactive Clustering GUI
python_package_command_line_name: interactive-clustering-gui
python_package_distribution_name: cognitivefactory-interactive-clustering-gui
python_package_import_name: cognitivefactory.interactive_clustering_gui
repository_name: interactive-clustering-gui
repository_namespace: cognitivefactory
repository_provider: github.com
use_precommit: false
