site_name: "Interactive Clustering GUI"
site_description: "A web application designed for NLP data annotation using Interactive Clustering methodology."
site_url: "https://cognitivefactory.github.io/interactive-clustering-gui"
repo_url: "https://github.com/cognitivefactory/interactive-clustering-gui"
repo_name: "cognitivefactory/interactive-clustering-gui"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/cognitivefactory/interactive_clustering_gui]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Examples:
  - Demo projects: examples/README.md
  - Analysis preparation: notebooks/README.md
  - Analysis notebook: notebooks/analysis.ipynb
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocs-jupyter:
    include: ["*.ipynb"]
    ignore_h1_titles: True
    remove_tag_config:
      remove_cell_tags:
        - hide
- mkdocstrings:
    watch:
    - src/cognitivefactory/

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/erwanschild
